//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/MessageInfo.proto
namespace netty
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageInfo")]
  public partial class MessageInfo : global::ProtoBuf.IExtensible
  {
    public MessageInfo() {}
    
    private netty.MESSAGE_ID _messageId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"messageId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public netty.MESSAGE_ID messageId
    {
      get { return _messageId; }
      set { _messageId = value; }
    }

    private netty.LoginReq _loginReq = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"loginReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.LoginReq loginReq
    {
      get { return _loginReq; }
      set { _loginReq = value; }
    }

    private netty.LoginResp _loginResp = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"loginResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.LoginResp loginResp
    {
      get { return _loginResp; }
      set { _loginResp = value; }
    }

    private netty.CreateRoomReq _createRoomReq = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"createRoomReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.CreateRoomReq createRoomReq
    {
      get { return _createRoomReq; }
      set { _createRoomReq = value; }
    }

    private netty.CreateRoomResp _createRoomResp = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"createRoomResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.CreateRoomResp createRoomResp
    {
      get { return _createRoomResp; }
      set { _createRoomResp = value; }
    }

    private netty.EntryRoomReq _entryRoomReq = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"entryRoomReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.EntryRoomReq entryRoomReq
    {
      get { return _entryRoomReq; }
      set { _entryRoomReq = value; }
    }

    private netty.EntryRoomResp _entryRoomResp = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"entryRoomResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.EntryRoomResp entryRoomResp
    {
      get { return _entryRoomResp; }
      set { _entryRoomResp = value; }
    }

    private netty.PostEntryRoom _postEntryRoom = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"postEntryRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostEntryRoom postEntryRoom
    {
      get { return _postEntryRoom; }
      set { _postEntryRoom = value; }
    }

    private netty.Player _player = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.Player player
    {
      get { return _player; }
      set { _player = value; }
    }

    private netty.DisbandReq _disbandReq = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"disbandReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.DisbandReq disbandReq
    {
      get { return _disbandReq; }
      set { _disbandReq = value; }
    }

    private netty.PostDisband _postDisband = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"postDisband", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostDisband postDisband
    {
      get { return _postDisband; }
      set { _postDisband = value; }
    }

    private netty.DisbandCheckReq _disbandCheckReq = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"disbandCheckReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.DisbandCheckReq disbandCheckReq
    {
      get { return _disbandCheckReq; }
      set { _disbandCheckReq = value; }
    }

    private netty.PostDisbandCheck _postDisbandCheck = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"postDisbandCheck", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostDisbandCheck postDisbandCheck
    {
      get { return _postDisbandCheck; }
      set { _postDisbandCheck = value; }
    }

    private netty.SettlementInfo _settlementInfo = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"settlementInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.SettlementInfo settlementInfo
    {
      get { return _settlementInfo; }
      set { _settlementInfo = value; }
    }

    private netty.DiscardReq _discardReq = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"discardReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.DiscardReq discardReq
    {
      get { return _discardReq; }
      set { _discardReq = value; }
    }

    private netty.PostDiscard _postDiscard = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"postDiscard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostDiscard postDiscard
    {
      get { return _postDiscard; }
      set { _postDiscard = value; }
    }

    private netty.DealReq _dealReq = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"dealReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.DealReq dealReq
    {
      get { return _dealReq; }
      set { _dealReq = value; }
    }

    private netty.DealResp _dealResp = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"dealResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.DealResp dealResp
    {
      get { return _dealResp; }
      set { _dealResp = value; }
    }

    private netty.GrabHostReq _grabHostReq = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"grabHostReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.GrabHostReq grabHostReq
    {
      get { return _grabHostReq; }
      set { _grabHostReq = value; }
    }

    private netty.MsgInfo _msgInfo = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"msgInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.MsgInfo msgInfo
    {
      get { return _msgInfo; }
      set { _msgInfo = value; }
    }

    private netty.PostGrabHostResp _postGrabHostResp = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"postGrabHostResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostGrabHostResp postGrabHostResp
    {
      get { return _postGrabHostResp; }
      set { _postGrabHostResp = value; }
    }

    private netty.PostDealOver _postDealOver = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"postDealOver", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostDealOver postDealOver
    {
      get { return _postDealOver; }
      set { _postDealOver = value; }
    }

    private netty.CreateNNRoomReq _createNNRoomReq = null;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"createNNRoomReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.CreateNNRoomReq createNNRoomReq
    {
      get { return _createNNRoomReq; }
      set { _createNNRoomReq = value; }
    }

    private netty.CreateNNRoomResp _createNNRoomResp = null;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"createNNRoomResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.CreateNNRoomResp createNNRoomResp
    {
      get { return _createNNRoomResp; }
      set { _createNNRoomResp = value; }
    }

    private netty.EntryNNRoomReq _entryNNRoomReq = null;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"entryNNRoomReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.EntryNNRoomReq entryNNRoomReq
    {
      get { return _entryNNRoomReq; }
      set { _entryNNRoomReq = value; }
    }

    private netty.EntryNNRoomResp _entryNNRoomResp = null;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"entryNNRoomResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.EntryNNRoomResp entryNNRoomResp
    {
      get { return _entryNNRoomResp; }
      set { _entryNNRoomResp = value; }
    }

    private netty.PostNNEntryRoom _postNNEntryRoom = null;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"postNNEntryRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostNNEntryRoom postNNEntryRoom
    {
      get { return _postNNEntryRoom; }
      set { _postNNEntryRoom = value; }
    }

    private netty.StartNNGameReq _startNNGame = null;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"startNNGame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.StartNNGameReq startNNGame
    {
      get { return _startNNGame; }
      set { _startNNGame = value; }
    }

    private netty.StartNNGameResp _startNNgameResp = null;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"startNNgameResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.StartNNGameResp startNNgameResp
    {
      get { return _startNNgameResp; }
      set { _startNNgameResp = value; }
    }

    private netty.PostStartNNGame _postStartNNGame = null;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"postStartNNGame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostStartNNGame postStartNNGame
    {
      get { return _postStartNNGame; }
      set { _postStartNNGame = value; }
    }

    private netty.NNPrepareReq _nnPrepareReq = null;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"nnPrepareReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.NNPrepareReq nnPrepareReq
    {
      get { return _nnPrepareReq; }
      set { _nnPrepareReq = value; }
    }

    private netty.PostNNDealResp _nnDealResp = null;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"nnDealResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostNNDealResp nnDealResp
    {
      get { return _nnDealResp; }
      set { _nnDealResp = value; }
    }

    private netty.StakeReq _stakeReq = null;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"stakeReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.StakeReq stakeReq
    {
      get { return _stakeReq; }
      set { _stakeReq = value; }
    }

    private netty.StakeResp _stakeResp = null;
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"stakeResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.StakeResp stakeResp
    {
      get { return _stakeResp; }
      set { _stakeResp = value; }
    }

    private netty.PostStakeResp _postStakeResp = null;
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"postStakeResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostStakeResp postStakeResp
    {
      get { return _postStakeResp; }
      set { _postStakeResp = value; }
    }

    private netty.NNShowCardsReq _nnShowCardsReq = null;
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"nnShowCardsReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.NNShowCardsReq nnShowCardsReq
    {
      get { return _nnShowCardsReq; }
      set { _nnShowCardsReq = value; }
    }

    private netty.NNShowCardsResp _nnShowCardsResp = null;
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"nnShowCardsResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.NNShowCardsResp nnShowCardsResp
    {
      get { return _nnShowCardsResp; }
      set { _nnShowCardsResp = value; }
    }

    private netty.PostNNShowCards _postNNShowCards = null;
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"postNNShowCards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostNNShowCards postNNShowCards
    {
      get { return _postNNShowCards; }
      set { _postNNShowCards = value; }
    }

    private netty.PostNNPrepareResp _postNNPrepareResp = null;
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"postNNPrepareResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostNNPrepareResp postNNPrepareResp
    {
      get { return _postNNPrepareResp; }
      set { _postNNPrepareResp = value; }
    }

    private netty.PostStakeOver _postStakeOver = null;
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"postStakeOver", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostStakeOver postStakeOver
    {
      get { return _postStakeOver; }
      set { _postStakeOver = value; }
    }

    private netty.NNDissolutionReq _nnDissolutionReq = null;
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"nnDissolutionReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.NNDissolutionReq nnDissolutionReq
    {
      get { return _nnDissolutionReq; }
      set { _nnDissolutionReq = value; }
    }

    private netty.PostDissolutionResp _postDissolutionResp = null;
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"postDissolutionResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostDissolutionResp postDissolutionResp
    {
      get { return _postDissolutionResp; }
      set { _postDissolutionResp = value; }
    }

    private netty.NNAnswerDissolutionReq _nnAnswerDissolutionReq = null;
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"nnAnswerDissolutionReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.NNAnswerDissolutionReq nnAnswerDissolutionReq
    {
      get { return _nnAnswerDissolutionReq; }
      set { _nnAnswerDissolutionReq = value; }
    }

    private netty.PostAnswerDissolutionResult _PostAnswerDissolutionResult = null;
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"PostAnswerDissolutionResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostAnswerDissolutionResult PostAnswerDissolutionResult
    {
      get { return _PostAnswerDissolutionResult; }
      set { _PostAnswerDissolutionResult = value; }
    }

    private netty.PostDissolutionResult _postDissolutionResult = null;
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"postDissolutionResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostDissolutionResult postDissolutionResult
    {
      get { return _postDissolutionResult; }
      set { _postDissolutionResult = value; }
    }

    private netty.SendSoundReq _sendSoundReq = null;
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"sendSoundReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.SendSoundReq sendSoundReq
    {
      get { return _sendSoundReq; }
      set { _sendSoundReq = value; }
    }

    private netty.PostSendSoundResp _postSendSoundResp = null;
    [global::ProtoBuf.ProtoMember(47, IsRequired = false, Name=@"postSendSoundResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostSendSoundResp postSendSoundResp
    {
      get { return _postSendSoundResp; }
      set { _postSendSoundResp = value; }
    }

    private netty.SignOutReq _signOutReq = null;
    [global::ProtoBuf.ProtoMember(48, IsRequired = false, Name=@"signOutReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.SignOutReq signOutReq
    {
      get { return _signOutReq; }
      set { _signOutReq = value; }
    }

    private netty.ReEntryNNRoomReq _reEntryNNRoomReq = null;
    [global::ProtoBuf.ProtoMember(49, IsRequired = false, Name=@"reEntryNNRoomReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.ReEntryNNRoomReq reEntryNNRoomReq
    {
      get { return _reEntryNNRoomReq; }
      set { _reEntryNNRoomReq = value; }
    }

    private netty.PostUnusualQuit _postUnusualQuit = null;
    [global::ProtoBuf.ProtoMember(50, IsRequired = false, Name=@"postUnusualQuit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostUnusualQuit postUnusualQuit
    {
      get { return _postUnusualQuit; }
      set { _postUnusualQuit = value; }
    }

    private netty.PostPlayerOnline _postPlayerOnline = null;
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"postPlayerOnline", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostPlayerOnline postPlayerOnline
    {
      get { return _postPlayerOnline; }
      set { _postPlayerOnline = value; }
    }

    private netty.PostPlayerOffline _postPlayerOffline = null;
    [global::ProtoBuf.ProtoMember(52, IsRequired = false, Name=@"postPlayerOffline", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.PostPlayerOffline postPlayerOffline
    {
      get { return _postPlayerOffline; }
      set { _postPlayerOffline = value; }
    }

    private netty.ReConnectReq _reConnectReq = null;
    [global::ProtoBuf.ProtoMember(53, IsRequired = false, Name=@"reConnectReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.ReConnectReq reConnectReq
    {
      get { return _reConnectReq; }
      set { _reConnectReq = value; }
    }

    private netty.ReConnectResp _reConnectResp = null;
    [global::ProtoBuf.ProtoMember(54, IsRequired = false, Name=@"reConnectResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.ReConnectResp reConnectResp
    {
      get { return _reConnectResp; }
      set { _reConnectResp = value; }
    }

    private netty.HeartBeatReq _heartBeatReq = null;
    [global::ProtoBuf.ProtoMember(55, IsRequired = false, Name=@"heartBeatReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.HeartBeatReq heartBeatReq
    {
      get { return _heartBeatReq; }
      set { _heartBeatReq = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginReq")]
  public partial class LoginReq : global::ProtoBuf.IExtensible
  {
    public LoginReq() {}
    
    private string _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }

    private int _playerid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }

    private string _clientinfos = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"clientinfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clientinfos
    {
      get { return _clientinfos; }
      set { _clientinfos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerBaseInfo")]
  public partial class PlayerBaseInfo : global::ProtoBuf.IExtensible
  {
    public PlayerBaseInfo() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _imgUrl = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"imgUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string imgUrl
    {
      get { return _imgUrl; }
      set { _imgUrl = value; }
    }

    private int _cardNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cardNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardNum
    {
      get { return _cardNum; }
      set { _cardNum = value; }
    }

    private string _wxopenid = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"wxopenid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string wxopenid
    {
      get { return _wxopenid; }
      set { _wxopenid = value; }
    }
    private string _token;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResp")]
  public partial class LoginResp : global::ProtoBuf.IExtensible
  {
    public LoginResp() {}
    
    private netty.PlayerBaseInfo _playerBaseInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerBaseInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public netty.PlayerBaseInfo playerBaseInfo
    {
      get { return _playerBaseInfo; }
      set { _playerBaseInfo = value; }
    }

    private string _shareurl = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"shareurl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string shareurl
    {
      get { return _shareurl; }
      set { _shareurl = value; }
    }
    private int _playerState;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerState
    {
      get { return _playerState; }
      set { _playerState = value; }
    }

    private int _roomId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoomReq")]
  public partial class CreateRoomReq : global::ProtoBuf.IExtensible
  {
    public CreateRoomReq() {}
    
    private int _games;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"games", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int games
    {
      get { return _games; }
      set { _games = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _playerId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoomResp")]
  public partial class CreateRoomResp : global::ProtoBuf.IExtensible
  {
    public CreateRoomResp() {}
    
    private int _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EntryRoomReq")]
  public partial class EntryRoomReq : global::ProtoBuf.IExtensible
  {
    public EntryRoomReq() {}
    
    private int _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EntryRoomResp")]
  public partial class EntryRoomResp : global::ProtoBuf.IExtensible
  {
    public EntryRoomResp() {}
    
    private netty.RoomInfo _roomInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public netty.RoomInfo roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }
    private int _order;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int order
    {
      get { return _order; }
      set { _order = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostEntryRoom")]
  public partial class PostEntryRoom : global::ProtoBuf.IExtensible
  {
    public PostEntryRoom() {}
    
    private netty.Player _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public netty.Player player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomInfo")]
  public partial class RoomInfo : global::ProtoBuf.IExtensible
  {
    public RoomInfo() {}
    
    private int _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private readonly global::System.Collections.Generic.List<netty.Player> _players = new global::System.Collections.Generic.List<netty.Player>();
    [global::ProtoBuf.ProtoMember(2, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<netty.Player> players
    {
      get { return _players; }
    }
  

    private int _multiple = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"multiple", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int multiple
    {
      get { return _multiple; }
      set { _multiple = value; }
    }

    private int _playedGames = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"playedGames", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playedGames
    {
      get { return _playedGames; }
      set { _playedGames = value; }
    }

    private int _totalGames = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"totalGames", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalGames
    {
      get { return _totalGames; }
      set { _totalGames = value; }
    }

    private int _currentPlayerId = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"currentPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int currentPlayerId
    {
      get { return _currentPlayerId; }
      set { _currentPlayerId = value; }
    }

    private int _bankerId = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"bankerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bankerId
    {
      get { return _bankerId; }
      set { _bankerId = value; }
    }
    private bool _isDisband;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"isDisband", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isDisband
    {
      get { return _isDisband; }
      set { _isDisband = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _agreePlayerIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"agreePlayerIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> agreePlayerIds
    {
      get { return _agreePlayerIds; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _refusePlayerIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"refusePlayerIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> refusePlayerIds
    {
      get { return _refusePlayerIds; }
    }
  

    private int _startDisbandTime = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"startDisbandTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int startDisbandTime
    {
      get { return _startDisbandTime; }
      set { _startDisbandTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Player")]
  public partial class Player : global::ProtoBuf.IExtensible
  {
    public Player() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _imgUrl = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"imgUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string imgUrl
    {
      get { return _imgUrl; }
      set { _imgUrl = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private bool _isDz;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"isDz", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isDz
    {
      get { return _isDz; }
      set { _isDz = value; }
    }

    private int _order = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int order
    {
      get { return _order; }
      set { _order = value; }
    }

    private bool _isOnline = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"isOnline", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isOnline
    {
      get { return _isOnline; }
      set { _isOnline = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _pokerids = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"pokerids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> pokerids
    {
      get { return _pokerids; }
    }
  

    private netty.NNType _nntype = netty.NNType.NNT_ERROR;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"nntype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(netty.NNType.NNT_ERROR)]
    public netty.NNType nntype
    {
      get { return _nntype; }
      set { _nntype = value; }
    }

    private int _stakepoint = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"stakepoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stakepoint
    {
      get { return _stakepoint; }
      set { _stakepoint = value; }
    }

    private netty.NNStatus _status = netty.NNStatus.STATUS_NONE;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(netty.NNStatus.STATUS_NONE)]
    public netty.NNStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Poker")]
  public partial class Poker : global::ProtoBuf.IExtensible
  {
    public Poker() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private bool _isOut;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isOut", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isOut
    {
      get { return _isOut; }
      set { _isOut = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DisbandReq")]
  public partial class DisbandReq : global::ProtoBuf.IExtensible
  {
    public DisbandReq() {}
    
    private int _groupId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int groupId
    {
      get { return _groupId; }
      set { _groupId = value; }
    }
    private int _playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostDisband")]
  public partial class PostDisband : global::ProtoBuf.IExtensible
  {
    public PostDisband() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DisbandCheckReq")]
  public partial class DisbandCheckReq : global::ProtoBuf.IExtensible
  {
    public DisbandCheckReq() {}
    
    private bool _agree;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"agree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool agree
    {
      get { return _agree; }
      set { _agree = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostDisbandCheck")]
  public partial class PostDisbandCheck : global::ProtoBuf.IExtensible
  {
    public PostDisbandCheck() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SettlementData")]
  public partial class SettlementData : global::ProtoBuf.IExtensible
  {
    public SettlementData() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _gotscore;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gotscore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gotscore
    {
      get { return _gotscore; }
      set { _gotscore = value; }
    }
    private int _finalscore;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"finalscore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int finalscore
    {
      get { return _finalscore; }
      set { _finalscore = value; }
    }
    private bool _isWin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"isWin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isWin
    {
      get { return _isWin; }
      set { _isWin = value; }
    }

    private int _leaveCardNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"leaveCardNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int leaveCardNum
    {
      get { return _leaveCardNum; }
      set { _leaveCardNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SettlementInfo")]
  public partial class SettlementInfo : global::ProtoBuf.IExtensible
  {
    public SettlementInfo() {}
    
    private readonly global::System.Collections.Generic.List<netty.SettlementData> _players = new global::System.Collections.Generic.List<netty.SettlementData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<netty.SettlementData> players
    {
      get { return _players; }
    }
  
    private bool _isOver;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isOver", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isOver
    {
      get { return _isOver; }
      set { _isOver = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DiscardReq")]
  public partial class DiscardReq : global::ProtoBuf.IExtensible
  {
    public DiscardReq() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cardIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cardIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cardIds
    {
      get { return _cardIds; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _variableCardIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"variableCardIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> variableCardIds
    {
      get { return _variableCardIds; }
    }
  
    private int _cardsType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"cardsType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cardsType
    {
      get { return _cardsType; }
      set { _cardsType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostDiscard")]
  public partial class PostDiscard : global::ProtoBuf.IExtensible
  {
    public PostDiscard() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cardIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cardIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cardIds
    {
      get { return _cardIds; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _variableCardIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"variableCardIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> variableCardIds
    {
      get { return _variableCardIds; }
    }
  
    private int _remainderPokersNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"remainderPokersNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int remainderPokersNum
    {
      get { return _remainderPokersNum; }
      set { _remainderPokersNum = value; }
    }
    private int _nextDiscardPlayerId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"nextDiscardPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nextDiscardPlayerId
    {
      get { return _nextDiscardPlayerId; }
      set { _nextDiscardPlayerId = value; }
    }
    private bool _mustDiscard;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"mustDiscard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool mustDiscard
    {
      get { return _mustDiscard; }
      set { _mustDiscard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DealReq")]
  public partial class DealReq : global::ProtoBuf.IExtensible
  {
    public DealReq() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DealResp")]
  public partial class DealResp : global::ProtoBuf.IExtensible
  {
    public DealResp() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private readonly global::System.Collections.Generic.List<netty.Poker> _pokers = new global::System.Collections.Generic.List<netty.Poker>();
    [global::ProtoBuf.ProtoMember(2, Name=@"pokers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<netty.Poker> pokers
    {
      get { return _pokers; }
    }
  

    private netty.RoomInfo _roomInfo = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public netty.RoomInfo roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }
    private int _grabHost;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"grabHost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int grabHost
    {
      get { return _grabHost; }
      set { _grabHost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GrabHostReq")]
  public partial class GrabHostReq : global::ProtoBuf.IExtensible
  {
    public GrabHostReq() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostGrabHostResp")]
  public partial class PostGrabHostResp : global::ProtoBuf.IExtensible
  {
    public PostGrabHostResp() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }

    private int _hostPlayerId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hostPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hostPlayerId
    {
      get { return _hostPlayerId; }
      set { _hostPlayerId = value; }
    }
    private readonly global::System.Collections.Generic.List<netty.Poker> _pokers = new global::System.Collections.Generic.List<netty.Poker>();
    [global::ProtoBuf.ProtoMember(4, Name=@"pokers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<netty.Poker> pokers
    {
      get { return _pokers; }
    }
  

    private int _variable = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"variable", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int variable
    {
      get { return _variable; }
      set { _variable = value; }
    }

    private int _nextGrabPlayerId = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"nextGrabPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nextGrabPlayerId
    {
      get { return _nextGrabPlayerId; }
      set { _nextGrabPlayerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgInfo")]
  public partial class MsgInfo : global::ProtoBuf.IExtensible
  {
    public MsgInfo() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostDealOver")]
  public partial class PostDealOver : global::ProtoBuf.IExtensible
  {
    public PostDealOver() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateNNRoomReq")]
  public partial class CreateNNRoomReq : global::ProtoBuf.IExtensible
  {
    public CreateNNRoomReq() {}
    
    private int _games;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"games", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int games
    {
      get { return _games; }
      set { _games = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _playerId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private netty.BankerType _bankerType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"bankerType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public netty.BankerType bankerType
    {
      get { return _bankerType; }
      set { _bankerType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateNNRoomResp")]
  public partial class CreateNNRoomResp : global::ProtoBuf.IExtensible
  {
    public CreateNNRoomResp() {}
    
    private int _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EntryNNRoomReq")]
  public partial class EntryNNRoomReq : global::ProtoBuf.IExtensible
  {
    public EntryNNRoomReq() {}
    
    private int _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EntryNNRoomResp")]
  public partial class EntryNNRoomResp : global::ProtoBuf.IExtensible
  {
    public EntryNNRoomResp() {}
    
    private netty.RoomInfo _roomInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public netty.RoomInfo roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }
    private int _order;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int order
    {
      get { return _order; }
      set { _order = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostNNEntryRoom")]
  public partial class PostNNEntryRoom : global::ProtoBuf.IExtensible
  {
    public PostNNEntryRoom() {}
    
    private netty.Player _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public netty.Player player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartNNGameReq")]
  public partial class StartNNGameReq : global::ProtoBuf.IExtensible
  {
    public StartNNGameReq() {}
    
    private int _playerid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartNNGameResp")]
  public partial class StartNNGameResp : global::ProtoBuf.IExtensible
  {
    public StartNNGameResp() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostStartNNGame")]
  public partial class PostStartNNGame : global::ProtoBuf.IExtensible
  {
    public PostStartNNGame() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NNPrepareReq")]
  public partial class NNPrepareReq : global::ProtoBuf.IExtensible
  {
    public NNPrepareReq() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostNNDealResp")]
  public partial class PostNNDealResp : global::ProtoBuf.IExtensible
  {
    public PostNNDealResp() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _pokers = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"pokers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> pokers
    {
      get { return _pokers; }
    }
  
    private int _playedGames;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playedGames", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playedGames
    {
      get { return _playedGames; }
      set { _playedGames = value; }
    }
    private int _totalGames;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"totalGames", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalGames
    {
      get { return _totalGames; }
      set { _totalGames = value; }
    }
    private int _bankerId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"bankerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bankerId
    {
      get { return _bankerId; }
      set { _bankerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StakeReq")]
  public partial class StakeReq : global::ProtoBuf.IExtensible
  {
    public StakeReq() {}
    
    private int _playerid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private int _point;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int point
    {
      get { return _point; }
      set { _point = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StakeResp")]
  public partial class StakeResp : global::ProtoBuf.IExtensible
  {
    public StakeResp() {}
    
    private int _point;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int point
    {
      get { return _point; }
      set { _point = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostStakeResp")]
  public partial class PostStakeResp : global::ProtoBuf.IExtensible
  {
    public PostStakeResp() {}
    
    private int _playerid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private int _point;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int point
    {
      get { return _point; }
      set { _point = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NNShowCardsReq")]
  public partial class NNShowCardsReq : global::ProtoBuf.IExtensible
  {
    public NNShowCardsReq() {}
    
    private int _playerid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private bool _showAll;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"showAll", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool showAll
    {
      get { return _showAll; }
      set { _showAll = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NNShowCardsResp")]
  public partial class NNShowCardsResp : global::ProtoBuf.IExtensible
  {
    public NNShowCardsResp() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _pokers = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"pokers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> pokers
    {
      get { return _pokers; }
    }
  
    private netty.NNType _nntype;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nntype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public netty.NNType nntype
    {
      get { return _nntype; }
      set { _nntype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostNNShowCards")]
  public partial class PostNNShowCards : global::ProtoBuf.IExtensible
  {
    public PostNNShowCards() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _pokers = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"pokers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> pokers
    {
      get { return _pokers; }
    }
  
    private netty.NNType _nntype;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nntype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public netty.NNType nntype
    {
      get { return _nntype; }
      set { _nntype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostNNPrepareResp")]
  public partial class PostNNPrepareResp : global::ProtoBuf.IExtensible
  {
    public PostNNPrepareResp() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostStakeOver")]
  public partial class PostStakeOver : global::ProtoBuf.IExtensible
  {
    public PostStakeOver() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NNDissolutionReq")]
  public partial class NNDissolutionReq : global::ProtoBuf.IExtensible
  {
    public NNDissolutionReq() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostDissolutionResp")]
  public partial class PostDissolutionResp : global::ProtoBuf.IExtensible
  {
    public PostDissolutionResp() {}
    
    private int _playerid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NNAnswerDissolutionReq")]
  public partial class NNAnswerDissolutionReq : global::ProtoBuf.IExtensible
  {
    public NNAnswerDissolutionReq() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private bool _isAgree;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isAgree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isAgree
    {
      get { return _isAgree; }
      set { _isAgree = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostAnswerDissolutionResult")]
  public partial class PostAnswerDissolutionResult : global::ProtoBuf.IExtensible
  {
    public PostAnswerDissolutionResult() {}
    
    private int _agreeCnt;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"agreeCnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int agreeCnt
    {
      get { return _agreeCnt; }
      set { _agreeCnt = value; }
    }
    private int _disagreeCnt;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"disagreeCnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int disagreeCnt
    {
      get { return _disagreeCnt; }
      set { _disagreeCnt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostDissolutionResult")]
  public partial class PostDissolutionResult : global::ProtoBuf.IExtensible
  {
    public PostDissolutionResult() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendSoundReq")]
  public partial class SendSoundReq : global::ProtoBuf.IExtensible
  {
    public SendSoundReq() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _soundId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"soundId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int soundId
    {
      get { return _soundId; }
      set { _soundId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostSendSoundResp")]
  public partial class PostSendSoundResp : global::ProtoBuf.IExtensible
  {
    public PostSendSoundResp() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _soundId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"soundId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int soundId
    {
      get { return _soundId; }
      set { _soundId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SignOutReq")]
  public partial class SignOutReq : global::ProtoBuf.IExtensible
  {
    public SignOutReq() {}
    
    private int _playerid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReEntryNNRoomReq")]
  public partial class ReEntryNNRoomReq : global::ProtoBuf.IExtensible
  {
    public ReEntryNNRoomReq() {}
    
    private int _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostUnusualQuit")]
  public partial class PostUnusualQuit : global::ProtoBuf.IExtensible
  {
    public PostUnusualQuit() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostPlayerOnline")]
  public partial class PostPlayerOnline : global::ProtoBuf.IExtensible
  {
    public PostPlayerOnline() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostPlayerOffline")]
  public partial class PostPlayerOffline : global::ProtoBuf.IExtensible
  {
    public PostPlayerOffline() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReConnectReq")]
  public partial class ReConnectReq : global::ProtoBuf.IExtensible
  {
    public ReConnectReq() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _token;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReConnectResp")]
  public partial class ReConnectResp : global::ProtoBuf.IExtensible
  {
    public ReConnectResp() {}
    
    private bool _reLoginSuccessed;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"reLoginSuccessed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool reLoginSuccessed
    {
      get { return _reLoginSuccessed; }
      set { _reLoginSuccessed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeartBeatReq")]
  public partial class HeartBeatReq : global::ProtoBuf.IExtensible
  {
    public HeartBeatReq() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MESSAGE_ID")]
    public enum MESSAGE_ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_LoginReq", Value=1)]
      msg_LoginReq = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_LoginResp", Value=2)]
      msg_LoginResp = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_CreateRoomReq", Value=3)]
      msg_CreateRoomReq = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_CreateRoomResp", Value=4)]
      msg_CreateRoomResp = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_EntryRoomReq", Value=5)]
      msg_EntryRoomReq = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_EntryRoomResp", Value=6)]
      msg_EntryRoomResp = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostEntryRoom", Value=7)]
      msg_PostEntryRoom = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_Player", Value=8)]
      msg_Player = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_DisbandReq", Value=9)]
      msg_DisbandReq = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostDisband", Value=10)]
      msg_PostDisband = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_DisbandCheckReq", Value=11)]
      msg_DisbandCheckReq = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostDisbandCheck", Value=12)]
      msg_PostDisbandCheck = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_SettlementInfo", Value=13)]
      msg_SettlementInfo = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_DiscardReq", Value=14)]
      msg_DiscardReq = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostDiscard", Value=15)]
      msg_PostDiscard = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_DealReq", Value=16)]
      msg_DealReq = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_DealResp", Value=17)]
      msg_DealResp = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_GrabHostReq", Value=18)]
      msg_GrabHostReq = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostGrabHostResp", Value=19)]
      msg_PostGrabHostResp = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_MsgInfo", Value=20)]
      msg_MsgInfo = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostDealOver", Value=21)]
      msg_PostDealOver = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_CreateNNRoomReq", Value=22)]
      msg_CreateNNRoomReq = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_CreateNNRoomResp", Value=23)]
      msg_CreateNNRoomResp = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_EntryNNRoomReq", Value=24)]
      msg_EntryNNRoomReq = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_EntryNNRoomResp", Value=25)]
      msg_EntryNNRoomResp = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostNNEntryRoom", Value=26)]
      msg_PostNNEntryRoom = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_StartNNGameReq", Value=27)]
      msg_StartNNGameReq = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_StartNNGameResp", Value=28)]
      msg_StartNNGameResp = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostStartNNGame", Value=29)]
      msg_PostStartNNGame = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_NNPrepareReq", Value=30)]
      msg_NNPrepareReq = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostNNDealResp", Value=31)]
      msg_PostNNDealResp = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_StakeReq", Value=32)]
      msg_StakeReq = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_StakeResp", Value=33)]
      msg_StakeResp = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostStakeResp", Value=34)]
      msg_PostStakeResp = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_NNShowCardsReq", Value=35)]
      msg_NNShowCardsReq = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_NNShowCardsResp", Value=36)]
      msg_NNShowCardsResp = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostNNShowCards", Value=37)]
      msg_PostNNShowCards = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostNNPrepareResp", Value=38)]
      msg_PostNNPrepareResp = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostStakeOver", Value=39)]
      msg_PostStakeOver = 39,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_NNDissolutionReq", Value=40)]
      msg_NNDissolutionReq = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostDissolutionResp", Value=41)]
      msg_PostDissolutionResp = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_NNAnswerDissolutionReq", Value=42)]
      msg_NNAnswerDissolutionReq = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostAnswerDissolutionResult", Value=43)]
      msg_PostAnswerDissolutionResult = 43,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostDissolutionResult", Value=44)]
      msg_PostDissolutionResult = 44,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_SendSoundReq", Value=45)]
      msg_SendSoundReq = 45,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostSendSoundResp", Value=46)]
      msg_PostSendSoundResp = 46,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_SignOutReq", Value=47)]
      msg_SignOutReq = 47,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_ReEntryNNRoomReq", Value=48)]
      msg_ReEntryNNRoomReq = 48,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostUnusualQuit", Value=49)]
      msg_PostUnusualQuit = 49,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostPlayerOnline", Value=50)]
      msg_PostPlayerOnline = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_PostPlayerOffline", Value=51)]
      msg_PostPlayerOffline = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_HeartBeatReq", Value=52)]
      msg_HeartBeatReq = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_HeartBeatResp", Value=53)]
      msg_HeartBeatResp = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_ReConnectReq", Value=54)]
      msg_ReConnectReq = 54,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_ReConnectResp", Value=55)]
      msg_ReConnectResp = 55
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"NNType")]
    public enum NNType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NNT_ERROR", Value=0)]
      NNT_ERROR = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NNT_NONE", Value=1)]
      NNT_NONE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NNT_SPECIAL_NIU1", Value=2)]
      NNT_SPECIAL_NIU1 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NNT_SPECIAL_NIU2", Value=3)]
      NNT_SPECIAL_NIU2 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NNT_SPECIAL_NIU3", Value=4)]
      NNT_SPECIAL_NIU3 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NNT_SPECIAL_NIU4", Value=5)]
      NNT_SPECIAL_NIU4 = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NNT_SPECIAL_NIU5", Value=6)]
      NNT_SPECIAL_NIU5 = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NNT_SPECIAL_NIU6", Value=7)]
      NNT_SPECIAL_NIU6 = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NNT_SPECIAL_NIU7", Value=8)]
      NNT_SPECIAL_NIU7 = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NNT_SPECIAL_NIU8", Value=9)]
      NNT_SPECIAL_NIU8 = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NNT_SPECIAL_NIU9", Value=10)]
      NNT_SPECIAL_NIU9 = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NNT_SPECIAL_NIUNIU", Value=11)]
      NNT_SPECIAL_NIUNIU = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NNT_SPECIAL_NIUHUA", Value=12)]
      NNT_SPECIAL_NIUHUA = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NNT_SPECIAL_BOMEBOME", Value=13)]
      NNT_SPECIAL_BOMEBOME = 13
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"NNStatus")]
    public enum NNStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS_NONE", Value=0)]
      STATUS_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS_CREATE_ROOM", Value=1)]
      STATUS_CREATE_ROOM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS_ENTER_ROOM", Value=2)]
      STATUS_ENTER_ROOM = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS_BEGIN_PREPARE", Value=3)]
      STATUS_BEGIN_PREPARE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS_FINISH_PREPARE", Value=4)]
      STATUS_FINISH_PREPARE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS_BEGIN_STAKE", Value=5)]
      STATUS_BEGIN_STAKE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS_BEGIN_SHOWCARDS", Value=6)]
      STATUS_BEGIN_SHOWCARDS = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS_PREPARE_NEXT", Value=7)]
      STATUS_PREPARE_NEXT = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BankerType")]
    public enum BankerType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BT_NONE", Value=0)]
      BT_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BT_BAWANG", Value=1)]
      BT_BAWANG = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BT_LUNZHUANG", Value=2)]
      BT_LUNZHUANG = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BT_ZHUANZHUANG", Value=3)]
      BT_ZHUANZHUANG = 3
    }
  
}